name: Premake build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        vsversion: '2022'
    - uses: actions/checkout@v4
      with: 
        path: 'build'
        submodules: 'recursive'
    - uses: abel0b/setup-premake@v2.4
      with:
        version: "5.0.0-beta2"
    - name: Setup premake
      working-directory: ./build
      # Run premake5 to generate make
      run: premake5 --os=windows --gmcommon=./garrysmod_common vs2022
    - name: Build
      working-directory: ./build
      run: msbuild RTXFixesBinary.sln
    - name: Upload artifact
      uses: actions/upload-artifact@v4.5.0
      with: 
        path: ${{ github.workspace }}/build/bin/**